# Generated by Django 5.0.4 on 2024-05-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0007_rename_captured_at_capturedimage_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='spot_code',
            field=models.CharField(default='z', max_length=50),
        ),
    ]
