# Generated by Django 5.0.4 on 2024-05-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0002_parkingspot_spot_code_alter_bookedspot_spot_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingcenter',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
