# Generated by Django 5.0.4 on 2024-05-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0003_parkingcenter_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingcenter',
            name='contact',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingcenter',
            name='latitude',
            field=models.FloatField(default=1.1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingcenter',
            name='longitude',
            field=models.FloatField(default=1.22),
            preserve_default=False,
        ),
    ]
