# Generated by Django 5.0.4 on 2024-05-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0006_capturedimage_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capturedimage',
            old_name='captured_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='capturedimage',
            name='image_path',
        ),
        migrations.AddField(
            model_name='capturedimage',
            name='image',
            field=models.ImageField(default=1.1, upload_to='parking_spot_images/'),
            preserve_default=False,
        ),
    ]
